//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplomb.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataDiagramEntityType
    {
        public int ID { get; set; }
        public int DataDiagramID { get; set; }
        public int EntityTypeID { get; set; }
        public string Color { get; set; }
        public double PositionX { get; set; }
        public double PositionY { get; set; }
    
        public virtual DataDiagram DataDiagram { get; set; }
        public virtual EntityType EntityType { get; set; }
    }
}
