//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplomb.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity
    {
        public Entity()
        {
            this.FieldValues = new HashSet<FieldValue>();
            this.FieldValues_FKs = new HashSet<FieldValue_FK>();
            this.UserEntities = new HashSet<UserEntity>();
        }
    
        public int ID { get; set; }
        public int TypeID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        public virtual EntityType EntityType { get; set; }
        public virtual ICollection<FieldValue> FieldValues { get; set; }
        public virtual ICollection<FieldValue_FK> FieldValues_FKs { get; set; }
        public virtual ICollection<UserEntity> UserEntities { get; set; }
    }
}
