//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplomb.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldValue
    {
        public int ID { get; set; }
        public int EntityID { get; set; }
        public int FieldID { get; set; }
        public int FieldNumber { get; set; }
        public int ValueNumber { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual Field Field { get; set; }
        public virtual FieldValue_Bit FieldValues_Bit { get; set; }
        public virtual FieldValue_Date FieldValues_Date { get; set; }
        public virtual FieldValue_Decimal FieldValues_Decimal { get; set; }
        public virtual FieldValue_FK FieldValues_FK { get; set; }
        public virtual FieldValue_Int FieldValues_Int { get; set; }
        public virtual FieldValues_FreeText FieldValues_FreeText { get; set; }
        public virtual FieldValues_Text FieldValues_Text { get; set; }
    }
}
