//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplomb.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        public Field()
        {
            this.Mandatory = false;
            this.MinNumber = 1;
            this.MaxNumber = 1;
            this.FieldValues = new HashSet<FieldValue>();
            this.RightFields = new HashSet<RightField>();
            this.LayoutFields = new HashSet<LayoutField>();
        }
    
        public int ID { get; set; }
        public int EntityTypeID { get; set; }
        public int TypeID { get; set; }
        public string Name { get; set; }
        public int SortOrder { get; set; }
        public bool Mandatory { get; set; }
        public int MinNumber { get; set; }
        public Nullable<int> MaxNumber { get; set; }
        public Nullable<int> ForeignKeyEntityTypeID { get; set; }
        public Nullable<int> NumericDefault { get; set; }
        public Nullable<int> MinValue { get; set; }
        public Nullable<int> MaxValue { get; set; }
        public string TextDefault { get; set; }
        public string TextRegex { get; set; }
    
        public virtual EntityType EntityType { get; set; }
        public virtual FieldType FieldType { get; set; }
        public virtual ICollection<FieldValue> FieldValues { get; set; }
        public virtual EntityType ForeignKeyEntityType { get; set; }
        public virtual ICollection<RightField> RightFields { get; set; }
        public virtual ICollection<LayoutField> LayoutFields { get; set; }
    }
}
