//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplomb.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LayoutField
    {
        public int ID { get; set; }
        public int LayoutID { get; set; }
        public int FieldID { get; set; }
        public string NameOverride { get; set; }
        public int SortOrder { get; set; }
    
        public virtual Field Field { get; set; }
        public virtual Layout Layout { get; set; }
    }
}
