//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplomb.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.MenuItems = new HashSet<MenuItem>();
            this.Sections = new HashSet<Section>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int SortOrder { get; set; }
        public Nullable<int> ParentMenuItemID { get; set; }
    
        public virtual ICollection<MenuItem> MenuItems { get; set; }
        public virtual MenuItem ParentMenuItem { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
    }
}
