//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplomb.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public MenuItem()
        {
            this.ChildMenus = new HashSet<Menu>();
        }
    
        public int ID { get; set; }
        public int MenuID { get; set; }
        public int SortOrder { get; set; }
        public string Name { get; set; }
        public Nullable<int> PageID { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Page Page { get; set; }
        public virtual ICollection<Menu> ChildMenus { get; set; }
    }
}
