//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplomb.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public Permission()
        {
            this.RightEntityTypes = new HashSet<RightEntityType>();
            this.RightFields = new HashSet<RightField>();
            this.RightPages = new HashSet<RightPage>();
            this.UserEntities = new HashSet<UserEntity>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool CanView { get; set; }
        public bool CanEdit { get; set; }
    
        public virtual ICollection<RightEntityType> RightEntityTypes { get; set; }
        public virtual ICollection<RightField> RightFields { get; set; }
        public virtual ICollection<RightPage> RightPages { get; set; }
        public virtual ICollection<UserEntity> UserEntities { get; set; }
    }
}
