//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplomb.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Right
    {
        public Right()
        {
            this.RightEntityTypes = new HashSet<RightEntityType>();
            this.RightFields = new HashSet<RightField>();
            this.RoleRights = new HashSet<RoleRight>();
            this.RightPages = new HashSet<RightPage>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<RightEntityType> RightEntityTypes { get; set; }
        public virtual ICollection<RightField> RightFields { get; set; }
        public virtual ICollection<RoleRight> RoleRights { get; set; }
        public virtual ICollection<RightPage> RightPages { get; set; }
    }
}
