//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplomb.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEntity
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int EntityID { get; set; }
        public int PermissionID { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual User User { get; set; }
        public virtual Permission Permission { get; set; }
    }
}
