//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplomb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModel : DbContext
    {
        public DataModel()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Entity> Entities { get; set; }
        public virtual DbSet<EntityType> EntityTypes { get; set; }
        public virtual DbSet<Field> Fields { get; set; }
        public virtual DbSet<FieldType> FieldTypes { get; set; }
        public virtual DbSet<FieldValue> FieldValues { get; set; }
        public virtual DbSet<FieldValue_Bit> FieldValue_Bit { get; set; }
        public virtual DbSet<FieldValue_Date> FieldValue_Date { get; set; }
        public virtual DbSet<FieldValue_Decimal> FieldValue_Decimal { get; set; }
        public virtual DbSet<FieldValue_FK> FieldValue_FK { get; set; }
        public virtual DbSet<FieldValue_Int> FieldValue_Int { get; set; }
        public virtual DbSet<FieldValue_LongText> FieldValue_LongText { get; set; }
        public virtual DbSet<FieldValue_ShortText> FieldValue_ShortText { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<RightEntityType> RightEntityTypes { get; set; }
        public virtual DbSet<RightField> RightFields { get; set; }
        public virtual DbSet<Right> Rights { get; set; }
        public virtual DbSet<RoleRight> RoleRights { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserEntity> UserEntities { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<LayoutField> LayoutFields { get; set; }
        public virtual DbSet<Layout> Layouts { get; set; }
        public virtual DbSet<MenuItem> MenuItems { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<PageType> PageTypes { get; set; }
        public virtual DbSet<RightPage> RightPages { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
    }
}
