//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplomb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageType
    {
        public PageType()
        {
            this.Pages = new HashSet<Page>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int SortOrder { get; set; }
    
        public virtual ICollection<Page> Pages { get; set; }
    }
}
