//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplomb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RightEntityType
    {
        public int ID { get; set; }
        public int RightID { get; set; }
        public int EntityTypeID { get; set; }
        public int PermissionID { get; set; }
    
        public virtual EntityType EntityType { get; set; }
        public virtual Permission Permission { get; set; }
        public virtual Right Right { get; set; }
    }
}
